[package]
name = "ebpf-monitor"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[dependencies]
ebpf-monitor-common = { path = "../ebpf-monitor-common", features = ["user"] }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
aya-log = { workspace = true }
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
android_logger = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
toml = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
plain = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }
cargo_metadata = { workspace = true }
ebpf-monitor-ebpf = { path = "../ebpf-monitor-ebpf" }

[[bin]]
name = "ebpf-monitor"
path = "src/main.rs"
